#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server
# Install HAProxy
sudo apt-get update -y
sudo apt-get install haproxy -y

# Configure HAProxy
echo 'frontend http-in
        bind *:80
        default_backend servers
backend servers
        balance roundrobin
        server web-01 54.210.123.227:80 check
        server web-02 100.26.172.200:80 check
' >> /etc/haproxy/haproxy.cfg

echo 'ENABLED=1' >> /etc/default/haproxy
# start HAProxy
service haproxy start

# reload HAProxy configuration
service haproxy reload
