#!/usr/bin/env bash
# This script elements 'FizzBuzz' game


a=0

while [ $a -lt  100 ]
do
	(( a+=1 ))
	
	if [ $(( a%3 )) == 0 ] && [ $(( a%5 )) == 0 ]
	then
		echo "FizzBuzz"
	elif [ $(( a%3 )) == 0 ]
	then
		echo "Fizz"
	elif [ $(( a%5 ))  == 0 ]
	then
		echo "Buzz"
	else
		echo "$a"
	fi
done
